### ISSUE TITLE
Make Corner and Make End icons don't work (TypeError: 'module' object is not callable)

### ISSUE THREAD

**Issue by xan2622** [Jrome90/Make_Corner_End#2]
Blender version: 2.91
Add-on version: 0.3

The following error appears in the console after selecting two vertices and clicking on the **Make Corner** icon.

1. Select two vertices next to a corner
2. Click on the **Make Corner** icon
3. The new edges are not created and this error appears in the console:

```
Traceback (most recent call last):
  File "C:\Users\user01\Downloads\blender-2.91.0-windows64\2.91\scripts\addons\Make_Corner_End-Make_Corner_End\tools.py", line 48, in execute_operator
    op_func = BPyOpsSubModOp(module, func)
TypeError: 'module' object is not callable
```

![McF1qgCTHP](https://user-images.githubusercontent.com/1732773/103147265-f567a480-4753-11eb-8211-8e2c94f3792b.gif)

Note that after selecting the two vertices, if you right-click (the menu appears), clicking on "Make Corner" works.

![Annotation 2020-12-26 082316](https://user-images.githubusercontent.com/1732773/103147254-dec14d80-4753-11eb-992f-50ed2d2aae23.png)

**Comment by xan2622** [comment]
Note that the error also appears if you: 
1. select any vertex of the mesh
2. move the vertex 
3. Click CTRL+Z to undo

---

EDIT: I have also noticed that the **Make End** icon doesn't work either (same error).

**Comment by xan2622** [comment]
Blender version: 2.91
Add-on version: 0.4.0

With this 0.4.0 version, when I click on the "Make Corner" or "Make End" icons (in the left toolbar), here is what I see now: 

Make Corner
```
Warning: Tool 'builtin.select_box' not found for space 'INFO'.
Traceback (most recent call last):
  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Make_Corner_End-Make_Corner_End\tools.py", line 49, in execute_operator
    op_func(context_override,'INVOKE_DEFAULT')
  File "E:\blender_portable\2.91\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.mce.make_corner.poll() failed, context is incorrect
```


Make End
```
Warning: Tool 'builtin.select_box' not found for space 'INFO'.
Traceback (most recent call last):
  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Make_Corner_End-Make_Corner_End\tools.py", line 49, in execute_operator
    op_func(context_override,'INVOKE_DEFAULT')
  File "E:\blender_portable\2.91\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.mce.make_end.poll() failed, context is incorrect
```
