### ISSUE TITLE
Error appears after switching to Edit mode: Warning: Tool 'builtin.select_box' not found for space 'PREFERENCES'.

### ISSUE THREAD

**Issue by xan2622** [Jrome90/Make_Corner_End#3]
Blender version: 2.91
Add-on version: 0.3

1. Activate **Make Corner and Make End** in Preferences > Addons
2. In Object mode, select an object (for example: the default cube)
3. Switch to Edit Mode by pressing TAB
4. This message should appear in the console: 

```
Warning: Tool 'builtin.select_box' not found for space 'PREFERENCES'.
Traceback (most recent call last):
  File "C:\Users\user01\Downloads\blender-2.91.0-windows64\2.91\scripts\addons\Make_Corner_End-Make_Corner_End\tools.py", line 48, in execute_operator
    op_func = BPyOpsSubModOp(module, func)
TypeError: 'module' object is not callable

Warning: Tool 'builtin.select_box' not found for space 'PREFERENCES'.
Traceback (most recent call last):
  File "C:\Users\user01\Downloads\blender-2.91.0-windows64\2.91\scripts\addons\Make_Corner_End-Make_Corner_End\tools.py", line 48, in execute_operator
    op_func = BPyOpsSubModOp(module, func)
TypeError: 'module' object is not callable
```

**Comment by Jrome90** [comment]
This appears to be related to issue #2.

**Comment by xan2622** [comment]
Blender version: 2.91
Add-on version: 0.4.0

Here is what I see now (when I press TAB): 
```

Warning: Tool 'builtin.select_box' not found for space 'INFO'.
Traceback (most recent call last):
  File "C:\Users\user01\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Make_Corner_End-Make_Corner_End\tools.py", line 49, in execute_operator
    op_func(context_override,'INVOKE_DEFAULT')
  File "E:\blender_portable\2.91\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.mce.make_end.poll() failed, context is incorrect

Warning: Tool 'builtin.select_box' not found for space 'INFO'.
Traceback (most recent call last):
  File "C:\Users\user01\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Make_Corner_End-Make_Corner_End\tools.py", line 49, in execute_operator
    op_func(context_override,'INVOKE_DEFAULT')
  File "E:\blender_portable\2.91\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.mce.make_end.poll() failed, context is incorrect
```
